spring:
  cloud:
    gateway:
      routes:

        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/auth/**

        - id: hero
          uri: lb://hero
          predicates:
            - Path=/api/hero/**

        - id: event
          uri: lb://event
          predicates:
            - Path=/api/event/**,  /api/admin/event, /api/admin/event/**